---
title: "Read Data"
author: "Ryan Hastings"
date: "10/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse); library(vroom); library(janitor); library(sf); library(tigris)
```


```{r, message = F}
philly <- vroom("../data/phl_data.csv") %>% rename(fips_tract = FIPStract)
glimpse(philly)
```

```{r}
philly2 <- philly %>% 
  mutate(ctyfips = str_sub(FIPStract, 1, 5))

philly2$ctyfips %>% unique()
```


Counties/FIPS codes:
Bucks - 42017;
Chester - 42029;
Delaware - 42045;
Montgomery - 42091;
Philadelphia - 42101


```{r cache = T, message = F}
shapes <- tracts(state = 'PA', county = c("Bucks", "Chester", "Delaware", "Montgomery", "Philadelphia")) %>% 
  clean_names() %>% 
  mutate(fips_tract = as.numeric(paste0(statefp, countyfp, tractce)))
```

```{r}
philly_tracts <- full_join(philly, shapes) %>%
  mutate(included = if_else(is.na(p_white), 0, 1)) %>% 
  st_as_sf()
```


```{r}
ggplot(philly_tracts) +
  geom_sf(aes(fill = as.factor(included))) +
  scale_fill_manual(values = c("#6EA9E2", "#EE5ED1")) +
  labs(title = "Tracts Included in Christensen & Timmins (2020)", fill = "Included") +
  theme_bw()
```



